# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 18:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, verbose_name='Prenom')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Nom de famille')),
                ('link', models.SlugField(blank=True, max_length=20, null=True, unique=True, verbose_name='Lien')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Lieu')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('picture', models.ImageField(default='account/images/profile/default.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/joffrey/Documents/PycharmProject/societyhiker/account/static'), upload_to='account/images/profile', verbose_name='Image de profil')),
                ('cover', models.ImageField(default='account/images/cover/default.jpg', upload_to='account/images/cover', verbose_name='Image de couverture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
