# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, verbose_name='Pseudo')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Lieu')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
