# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='account/images/profile/default.jpg', upload_to='account/images/profile', verbose_name='Photo'),
        ),
    ]
