# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 18:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subhead', models.TextField(blank=True, null=True, verbose_name='Bandeau')),
                ('body', tinymce_4.fields.TinyMCEModelField(verbose_name='Article')),
                ('image', models.ImageField(default='articles/images/header/article/default.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/joffrey/Documents/PycharmProject/societyhiker/articles/static'), upload_to='articles/images/header/article/', verbose_name='Background photo')),
                ('video', models.SlugField(blank=True, default='header', max_length=20, null=True, verbose_name='Background video')),
                ('use_video', models.BooleanField(default=False, verbose_name='Utiliser video?')),
                ('link', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Lien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Titre')),
                ('link', models.SlugField(max_length=20, verbose_name='Lien')),
                ('image', models.ImageField(default='articles/images/header/category/default.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/joffrey/Documents/PycharmProject/societyhiker/articles/static'), upload_to='articles/images/header/category', verbose_name='Background photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('text', models.TextField(max_length=480, verbose_name='Commentaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
