# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce_4.fields.TinyMCEModelField(verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/images/header/default.jpg', upload_to='articles/images/header', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subhead',
            field=models.TextField(blank=True, null=True, verbose_name='Bandeau'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=480, verbose_name='Commentaire'),
        ),
    ]
